#!/bin/bash

rm -rf /var/lib/mysql/*
mysql_install_db
mysqld_safe &
mysqladmin --silent --wait=30 ping || exit 1
mysql -e "UPDATE mysql.user SET Password=PASSWORD('$MYSQL_ROOT_PASSWD') WHERE User='root'; FLUSH PRIVILEGES;"
