#!/bin/bash

rm -rf /var/lib/mysql
mysql_install_db 
mysqld_safe &
mysqladmin --silent --wait=30 ping || exit 1
mysql -e 'GRANT ALL PRIVILEGES ON *.* TO \"root\"@\"%\" WITH GRANT OPTION;'
mysqladmin -uroot -p $MYSQL_ROOT_PASSWD
